// <auto-generated />
namespace Gamification.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class tutorialchangenameoftable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tutorialchangenameoftable));
        
        string IMigrationMetadata.Id
        {
            get { return "201707161732483_tutorial change name of table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
